### ISSUE TITLE
The vae encoder of the first_stage_model

### ISSUE THREAD

**Issue by forgetable233** [Stability-AI/generative-models#345]
I'm using the sv3d_p model. I noticed that the vae encoder of the first_stage_model is not provided in the ckpt. 
I wonder what's the vae encoder of the first_stage_model while training?

**Comment by JiuTongBro** [comment]
Same question.

**Comment by pengc02** [comment]
Hi guys, i'm also focus on this. It seems that sv3d use the same encoder and decoder as svd, while svd's encoder an decoder is released on huggingface. You can refer to: https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt/tree/main/vae for the ckpt,  https://github.com/huggingface/diffusers/blob/v0.24.0-release/src/diffusers/models/autoencoder_kl_temporal_decoder.py for the model code, and  https://github.com/huggingface/diffusers/blob/v0.24.0-release/src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py for how to use.

**Comment by fengq1a0** [comment]
> Hi guys, i'm also focus on this. It seems that sv3d use the same encoder and decoder as svd, while svd's encoder is released on huggingface. You can refer to: https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt/tree/main/vae for the ckpt, https://github.com/huggingface/diffusers/blob/v0.24.0-release/src/diffusers/models/autoencoder_kl_temporal_decoder.py for the model code, and https://github.com/huggingface/diffusers/blob/v0.24.0-release/src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py for how to use.

Hi, I found this ckpt might be wrong. I try to encode the image and decode it with SV3D and svd-xt respectively. The svd-xt's decoder can produce the right result but SV3D's can not. Do you know how to solve this? The images are attached below.
Raw:
![image](https://github.com/Stability-AI/generative-models/assets/32392843/10ede5c4-bb8e-48bc-9c6c-ec2ca1d9e759)
SV3D decoder:
![image](https://github.com/Stability-AI/generative-models/assets/32392843/160468f7-dcbd-4f65-83e1-16e9d2a74fc4)
SVD-XT decoder:
![image](https://github.com/Stability-AI/generative-models/assets/32392843/a0ca74d6-de05-4931-a8cf-1abf0d7a5abc)

**Comment by chenshuo20** [comment]
@pengc02 thx! It helps.

**Comment by chenshuo20** [comment]
> Hi guys, i'm also focus on this. It seems that sv3d use the same encoder and decoder as svd, while svd's encoder is released on huggingface. You can refer to: https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt/tree/main/vae for the ckpt, https://github.com/huggingface/diffusers/blob/v0.24.0-release/src/diffusers/models/autoencoder_kl_temporal_decoder.py for the model code, and https://github.com/huggingface/diffusers/blob/v0.24.0-release/src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py for how to use.

Also I find that you can use such config to load the vae model:
```
vae_encoder_config:
      target: src.diffusers.models.autoencoders.autoencoder_kl_temporal_decoder.AutoencoderKLTemporalDecoder
      params:
        block_out_channels: [128, 256, 512, 512]
        layers_per_block: 2
        in_channels: 3
        out_channels: 3
        down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D"]
```
